import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {createStore} from '../store.mjs';
import {createPetServer} from '../server.mjs';
import {DEFAULT_GROWTH_TASKS,GROWTH_CATEGORIES,GROWTH_MODES,recommendMode} from '../growthCatalog.mjs';
import {validateGrowthProfile} from '../growthStore.mjs';
const catalog=JSON.parse(readFileSync(new URL('../rewards.json',import.meta.url),'utf8'));
const key=()=>randomUUID(), now=()=>new Date().toISOString();
function fresh(t,mode='school_basic'){const s=createStore(':memory:',catalog);t.after(()=>s.close());if(mode)s.growth.configure({age:6,mode,timeZone:'Asia/Shanghai'});return s;}
const manual=(extra={})=>({category:'responsibility',title:'整理约定的用品',delta:2,reason:'按清单和家长一起整理了用品',occurredAt:now(),basisConfirmed:true,idempotencyKey:key(),...extra});
function task(s,id='school_basic-health-1'){return s.growth.read(true).tasks.find(t=>t.id===id);}
const editable=t=>Object.fromEntries(['id','title','category','modes','points','condition','assistance','reasonExample','frequency','dailyLimit','steps','active','archived'].map(k=>[k,t[k]]));
function activate(s,id){const t=task(s,id);s.growth.saveTask({...editable(t),active:true,expectedRevision:t.revision});return task(s,id);}
const forTask=(t,extra={})=>({taskId:t.id,expectedRevision:t.revision,delta:t.points,reason:t.reasonExample||'按约定完成这个步骤',occurredAt:now(),basisConfirmed:true,idempotencyKey:key(),...extra});
const error=(fn,status)=>assert.throws(fn,e=>e.status===status);

test('growth: 六类并列，三种模式共66条有依据与示例的预设',()=>{assert.equal(GROWTH_CATEGORIES.length,6);assert.equal(GROWTH_MODES.length,3);assert.equal(DEFAULT_GROWTH_TASKS.length,66);for(const m of GROWTH_MODES)for(const c of GROWTH_CATEGORIES){const ts=DEFAULT_GROWTH_TASKS.filter(t=>t.modes.includes(m.id)&&t.category===c.id);assert.equal(ts.length,m.id==='preschool'?5:3);for(const t of ts){assert.ok(t.condition&&t.assistance&&t.reasonExample&&t.sourceIds.length);assert.ok([1,2,3,5].includes(t.points));}}assert.equal(new Set(DEFAULT_GROWTH_TASKS.map(t=>t.id)).size,66);});
test('growth: 年龄建议不等于锁定，初始化必须明确填写年龄与模式',()=>{assert.equal(recommendMode(6,false),'preschool');assert.equal(recommendMode(6,true),'school_basic');assert.equal(recommendMode(9),'school_advanced');for(const age of [undefined,2,11,6.5,'6'])error(()=>validateGrowthProfile({age,mode:'school_basic'}),400);error(()=>validateGrowthProfile({age:6}),400);assert.equal(validateGrowthProfile({age:9,mode:'preschool'}).mode,'preschool');error(()=>validateGrowthProfile({age:6,mode:'school_basic',timeZone:'not/a/timezone'}),400);});
test('growth: 旧库不推测年龄、不改原流水和余额、可手动归类',t=>{const s=fresh(t,null);s.points({delta:20,reason:'旧加分',idempotencyKey:key()});const record=s.snapshot(true).ledger.find(r=>r.kind==='earn'),before=s.snapshot();assert.equal(s.growth.profile(),null);assert.equal(record.growthCategory,null);error(()=>s.growth.award(manual()),409);s.growth.configure({age:7,mode:'school_basic',timeZone:'UTC'});s.growth.classify({recordId:record.id,category:'learning',reason:'家长核对原记录后确认',idempotencyKey:key()});assert.equal(s.snapshot().balance,before.balance);assert.equal(s.snapshot().lifetime,before.lifetime);assert.equal(s.history({category:'learning'}).entries[0].growthSnapshot.legacy,true);assert.equal(s.growth.read(true).unclassified,0);error(()=>s.growth.classify({recordId:record.id,category:'health',reason:'重复',idempotencyKey:key()}),409);});
test('growth: 分值白名单、真实理由、明确依据、成年帮助不减分',t=>{const s=fresh(t);for(const delta of [-5,-1,4,10,0.5,'2'])error(()=>s.growth.award(manual({delta})),400);error(()=>s.growth.award(manual({reason:' '})),400);error(()=>s.growth.award(manual({basisConfirmed:false})),400);error(()=>s.growth.award(manual({category:'obedience'})),400);error(()=>s.growth.award(manual({delta:5})),400);s.growth.award(manual({assistance:'家长共同完成'}));assert.equal(s.snapshot().balance,2);s.growth.award(manual({delta:5,scoreReason:'事先约定的小挑战'}));assert.equal(s.snapshot().balance,7);});
test('growth: 同一请求幂等，重用ID不同内容拒绝，零分只保存回忆',t=>{const s=fresh(t),a=manual();s.growth.award(a);s.growth.award(a);assert.equal(s.snapshot().balance,2);error(()=>s.growth.award({...a,reason:'另一个理由'}),409);s.growth.award(manual({delta:0}));assert.equal(s.snapshot().lifetime,2);assert.equal(s.history({kind:'observation'}).total,1);assert.equal(s.growth.read(true).summary.find(r=>r.category==='responsibility').count,2);});
test('growth: 项目日限与家庭时区，重试不会重复发放',t=>{const s=fresh(t),t1=task(s);const a=forTask(t1,{occurredAt:'2026-01-01T16:30:00Z'});s.growth.award(a);s.growth.award(a);error(()=>s.growth.award(forTask(t1,{occurredAt:'2026-01-02T03:30:00Z'})),409);s.growth.award(forTask(t1,{occurredAt:'2026-01-01T15:30:00Z'}));assert.equal(s.snapshot().balance,4);const days=s.history({kind:'earn'}).entries.map(r=>r.awardDay).sort();assert.deepEqual(days,['2026-01-01','2026-01-02']);error(()=>s.growth.award(manual({occurredAt:'not-a-date'})),400);error(()=>s.growth.award(manual({occurredAt:'2026-01-01T12:00:00'})),400);error(()=>s.growth.award(manual({occurredAt:new Date(Date.now()+3600000).toISOString()})),400);});
test('growth: 模式与年龄更新不替换目标，不清空数据，旧版本不可覆盖',t=>{const s=fresh(t);const target=activate(s,'school_basic-health-1');s.growth.award(forTask(target));const before=s.snapshot();s.growth.configure({age:9,expectedRevision:1});assert.equal(s.growth.profile().mode,'school_basic');s.growth.configure({mode:'school_advanced',expectedRevision:2});const after=s.snapshot();assert.equal(after.balance,before.balance);assert.deepEqual(after.owned,before.owned);assert.equal(task(s).active,true);assert.equal(s.history({kind:'earn'}).entries[0].growthSnapshot.mode,'school_basic');error(()=>s.growth.configure({mode:'preschool',expectedRevision:1}),409);});
test('growth: 保存预设采用版本检查，历史完成条件和分值快照保持不变',t=>{const s=fresh(t),old=task(s);s.growth.award(forTask(old));s.growth.saveTask({...editable(old),title:'调整后的标题',condition:'下次采用另一条件',points:3,expectedRevision:old.revision});error(()=>s.growth.award(forTask(old,{occurredAt:'2026-01-01T00:00:00Z'})),409);const rec=s.history({kind:'earn'}).entries[0];assert.equal(rec.growthSnapshot.task.condition,old.condition);assert.equal(rec.delta,2);error(()=>s.growth.saveTask({...editable(old),expectedRevision:old.revision}),409);});
test('growth: 学龄孩子提交须家长确认，暂停/改模式不改待确认的规则快照',t=>{const s=fresh(t),original=activate(s,'school_basic-health-1'),at=now(),submission={taskId:original.id,expectedRevision:original.revision,reason:'我按约定完成了',occurredAt:at,idempotencyKey:key()};s.growth.submit(submission);s.growth.submit(submission);assert.equal(s.snapshot().balance,0);error(()=>s.growth.submit({...submission,idempotencyKey:key()}),409);error(()=>s.growth.award(forTask(original)),409);const r=s.growth.read(true).submissions[0];s.growth.saveTask({...editable(original),points:5,active:false,expectedRevision:original.revision});s.growth.configure({mode:'preschool',expectedRevision:1});s.growth.award(forTask(original,{submissionId:r.id,occurredAt:at}));assert.equal(s.snapshot().balance,2);assert.equal(s.growth.read().submissions.length,0);assert.equal(s.history({kind:'earn'}).entries[0].growthSnapshot.task.points,2);});
test('growth: 学前不能自行提交；未启用项目不能提交；取消不扣分',t=>{const s=fresh(t,'preschool'),t1=activate(s,'preschool-health-1');error(()=>s.growth.submit({taskId:t1.id,expectedRevision:t1.revision,reason:'',occurredAt:now(),idempotencyKey:key()}),403);s.growth.configure({mode:'school_basic',expectedRevision:1});error(()=>s.growth.submit({taskId:'school_basic-health-1',expectedRevision:1,reason:'',occurredAt:now(),idempotencyKey:key()}),403);s.growth.submit({taskId:t1.id,expectedRevision:t1.revision,reason:'',occurredAt:now(),idempotencyKey:key()});s.growth.cancelSubmission({id:s.growth.read(true).submissions[0].id,reason:'和孩子商量后先暂停',idempotencyKey:key()});assert.equal(s.snapshot().balance,0);assert.equal(s.growth.read().submissions.length,0);});
function project(s){s.growth.saveTask({id:'custom-story',title:'小故事书',category:'creativity',modes:['school_advanced'],points:5,condition:'按约定完成三个小步骤',assistance:'允许口述、绘画与家长帮助',frequency:'once',dailyLimit:1,steps:[{id:'idea',title:'确定故事',points:1},{id:'make',title:'制作一部分',points:3},{id:'review',title:'回看一处',points:1}],active:true});return task(s,'custom-story');}
test('growth: 多日步骤只结算一次，暂停保留积分，不能重复领总分',t=>{const s=fresh(t),p=project(s);error(()=>s.growth.award(forTask(p)),400);s.growth.award(forTask(p,{stepId:'idea',delta:1}));error(()=>s.growth.award(forTask(p,{stepId:'idea',delta:1})),409);error(()=>s.growth.award(forTask(p,{stepId:'make',delta:5,scoreReason:'临时改'})),400);s.growth.award(forTask(p,{stepId:'make',delta:3}));assert.equal(s.snapshot().balance,4);s.growth.saveTask({...editable(p),active:false,expectedRevision:p.revision});assert.equal(s.snapshot().balance,4);error(()=>s.growth.saveTask({...editable(task(s,p.id)),steps:[{id:'idea',title:'改写',points:5}],expectedRevision:2}),409);});
test('growth: 更正必须关联原记录、不可重复，余额不足不会回收物品',t=>{const s=fresh(t);s.growth.award(manual());const r=s.history({kind:'earn'}).entries[0],payload={recordId:r.id,reason:'误录到重复日期',idempotencyKey:key()};s.growth.correct(payload);s.growth.correct(payload);assert.equal(s.snapshot().balance,0);assert.equal(s.snapshot().lifetime,2);assert.equal(s.growth.read().recent.length,0);assert.equal(s.history({kind:'earn'}).total,1);error(()=>s.growth.correct({...payload,idempotencyKey:key()}),409);s.growth.award(manual());const next=s.history({kind:'earn'}).entries[0];s.points({delta:-2,reason:'旧接口兼容性测试扣除余额',idempotencyKey:key()});error(()=>s.growth.correct({recordId:next.id,reason:'误录',idempotencyKey:key()}),409);assert.equal(s.snapshot().balance,0);});
test('growth: 单次分类无积分套利，服务端拒绝多余字段和SQL式分类',t=>{const s=fresh(t);error(()=>s.growth.award({...manual(),lifetime:999}),400);error(()=>s.growth.award(manual({category:"health' OR 1=1"})),400);error(()=>s.history({category:'unknown'}),400);const t1=task(s);error(()=>s.growth.saveTask({...editable(t1),expectedRevision:t1.revision,params:{unsafe:true}}),400);assert.equal(s.snapshot().balance,0);});
test('growth: 成长记录、任务、规则快照、模式与幂等请求重启后保留',()=>{const dir=mkdtempSync(join(tmpdir(),'meow-growth-'));try{const path=join(dir,'pet.sqlite');let s=createStore(path,catalog);s.growth.configure({age:8,mode:'school_basic',timeZone:'America/Phoenix'});const t1=activate(s,'school_basic-health-1'),a=forTask(t1);s.growth.award(a);s.close();s=createStore(path,catalog);s.growth.award(a);assert.equal(s.snapshot().balance,2);assert.equal(s.growth.profile().age,8);assert.equal(task(s).active,true);assert.equal(s.growth.read(true).tasks.length,66);const exported=s.exportData();assert.equal(exported.growth.schemaVersion,1);assert.ok(exported.growth.audit.length);assert.ok(!JSON.stringify(exported).includes('tokenHash'));s.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('growth: 从原始六字段流水库迁移，保留原始时间、金额和所有权',()=>{const dir=mkdtempSync(join(tmpdir(),'meow-old-'));try{const path=join(dir,'old.sqlite');const db=new DatabaseSync(path);db.exec("CREATE TABLE ledger(id TEXT PRIMARY KEY,kind TEXT NOT NULL,delta INTEGER NOT NULL,reason TEXT NOT NULL,rewardId TEXT,createdAt TEXT NOT NULL); INSERT INTO ledger VALUES('old-1','earn',5,'旧记录',NULL,'2025-01-01T00:00:00.000Z')");db.close();const s=createStore(path,catalog);assert.equal(s.growth.profile(),null);const r=s.history({kind:'earn'}).entries[0];assert.equal(r.id,'old-1');assert.equal(r.delta,5);assert.equal(r.growthCategory,null);assert.equal(r.createdAt,'2025-01-01T00:00:00.000Z');s.close();}finally{rmSync(dir,{recursive:true,force:true});}});

async function server(t){const app=await createPetServer({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const origin=`http://127.0.0.1:${app.server.address().port}`,sessions={};async function req(path,method='GET',payload,role='parent',csrf){const auth=sessions[role]||{};const r=await fetch(origin+path,{method,headers:{...(payload?{'Content-Type':'application/json','X-Meow-Client':'points-pet','X-CSRF-Token':csrf??auth.csrf??''}:{}),Cookie:auth.cookie??''},...(payload?{body:JSON.stringify(payload)}:{})});return {status:r.status,data:await r.json(),headers:r.headers};}
  const init={setupToken:app.setupToken,pin:'864209',childCode:'2468',childName:'测试孩子',petName:'测试猫'};
  assert.equal((await req('/api/parent/setup','POST',init)).status,400);
  const setup=await req('/api/parent/setup','POST',{...init,age:6,mode:'school_basic',timeZone:'UTC'});assert.equal(setup.status,200);sessions.parent={cookie:setup.headers.get('set-cookie').split(';')[0],csrf:setup.data.csrf};const login=await req('/api/child/login','POST',{code:'2468'});sessions.child={cookie:login.headers.get('set-cookie').split(';')[0],csrf:login.data.csrf};return {app,req};}
test('growth HTTP: 初始化与六类读写端到端、CSRF和角色权限',async t=>{const {app,req}=await server(t);assert.equal((await req('/api/parent/growth')).data.tasks.length,66);assert.equal((await req('/api/growth','GET',undefined,'child')).data.tasks.length,0);for(const route of ['award','classify','correct','cancel'])assert.equal((await req(`/api/parent/growth/${route}`,'POST',manual(),'child')).status,401);assert.equal((await req('/api/parent/growth/award','POST',manual(),'parent','bad')).status,403);const a=manual();assert.equal((await req('/api/parent/growth/award','POST',a)).status,200);assert.equal((await req('/api/parent/growth/award','POST',a)).status,200);assert.equal((await req('/api/growth','GET',undefined,'child')).data.summary.find(r=>r.category==='responsibility').count,1);assert.equal((await req('/api/history?category=responsibility','GET',undefined,'child')).data.total,1);assert.equal((await req('/api/parent/growth/profile','PUT',{age:9,mode:'school_advanced',expectedRevision:1})).status,200);assert.equal(app.store.snapshot().balance,2);});
test('growth HTTP: 待确认提交在服务端单次结算，孩子不能伪造年龄或积分',async t=>{const {app,req}=await server(t);const t1=activate(app.store,'school_basic-health-1'),at=now();assert.equal((await req('/api/growth/submit','POST',{taskId:t1.id,expectedRevision:t1.revision,reason:'我完成了',occurredAt:at,idempotencyKey:key()},'child')).status,200);assert.equal(app.store.snapshot().balance,0);const r=app.store.growth.read(true).submissions[0];const a=forTask(t1,{occurredAt:at,submissionId:r.id});const results=await Promise.all(Array.from({length:4},()=>req('/api/parent/growth/award','POST',a)));assert.ok(results.every(r=>r.status===200));assert.equal(app.store.snapshot().balance,2);assert.equal((await req('/api/parent/growth/profile','PUT',{age:10,mode:'school_advanced',expectedRevision:1},'child')).status,401);});
