import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page = await browser.newPage({viewport:{width:1280,height:900}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
mkdirSync('output/cat-contacts',{recursive:true});
try {
  await page.goto(process.env.CAT_TEST_URL || 'http://127.0.0.1:8793');
  await page.waitForFunction(()=>window.__toyWorld && window.render_game_to_text);
  await page.evaluate(()=>window.__setParams({pose:'standing'}));
  const result = await page.evaluate(async()=>{
    const world=window.__toyWorld();
    const CANNON=await import('/node_modules/cannon-es/dist/cannon-es.js');
    const sphere=world.catDiagnostics().spheres[1];
    const ball=world.toys.find(t=>t.kind==='ball');
    for(const t of world.toys) if(t!==ball) t.body.position.set(8,-10,8);
    window.advanceTime(1600);
    const before=world.catDiagnostics().contactCount;
    ball.body.position.set(sphere.x+sphere.r+ball.radius+.08,sphere.y,sphere.z);
    ball.body.velocity.set(-3,0,0); ball.body.wakeUp();
    window.advanceTime(280);
    const hit=world.catDiagnostics();
    const feedback=document.querySelector('#scene-speech-bubble').textContent;
    const rebound=ball.body.velocity.x;
    window.advanceTime(300);
    const repeated=world.catDiagnostics().contactCount;
    const obstacle=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(.3,2,.3))});
    obstacle.position.set(sphere.x+sphere.r+.15,1,sphere.z);
    world.world.addBody(obstacle);
    const old=JSON.parse(window.render_game_to_text()).cat.position;
    window.advanceTime(20);
    const blocked=JSON.parse(window.render_game_to_text()).cat.position;
    world.world.removeBody(obstacle);
    return {before,hit,repeated,feedback,rebound,old,blocked};
  });
  assert.ok(result.hit.contactCount>result.before,'impact feedback fires');
  assert.equal(result.repeated,result.hit.contactCount,'cooldown suppresses repeated contact');
  assert.ok(result.rebound>0,'ball rebounds');
  assert.ok(result.feedback.length>0,'cat speech visible');
  assert.ok(result.blocked[0]<result.old[0]-.02,'solid obstacle blocks the cat');
  await page.screenshot({path:'output/cat-contacts/interaction.png'});
  const movement=await page.evaluate(async()=>{
    const world=window.__toyWorld();
    const CANNON=await import('/node_modules/cannon-es/dist/cannon-es.js');
    const wall=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(3,2,.1))});
    wall.position.set(0,1,1.6); world.world.addBody(wall);
    window.__setAnimation({enabled:true,stateMachine:true});
    window.__setMotionKey('KeyW',true); window.advanceTime(3000);
    window.__setMotionKey('KeyW',false);
    const stopped=JSON.parse(window.render_game_to_text()).cat.position[2];
    world.world.removeBody(wall);
    window.__setMotionKey('KeyW',true); window.advanceTime(600); window.__setMotionKey('KeyW',false);
    const resumed=JSON.parse(window.render_game_to_text()).cat.position[2];
    return {stopped,resumed};
  });
  assert.ok(movement.stopped < 1,'walking is blocked by the wall');
  assert.ok(movement.resumed > movement.stopped + .2,'walking resumes after removing the wall');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result,movement},null,2));
} finally { await browser.close(); }
